<a href="https://colab.research.google.com/github/Asiiifa/Data-science-python-/blob/main/NBA(basketball)_EDA_Python_day_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
t=pd.read_csv('/content/nba.csv.csv')
t

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [5]:
a=t.Position.unique()
a

array(['PG', 'SF', 'SG', 'PF', 'C'], dtype=object)

In [6]:
t.Team.unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz'],
      dtype=object)

In [7]:
t.Age.unique ()

array([25., 27., 22., 29., 21., 24., 20., 26., 28., 32., 23., 30., 33.,
       34., 37., 36., 31., 38., 39., 19., 35., 40.])

In [8]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [9]:
t.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [10]:
t.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [11]:
t.describe ()

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [12]:
#data cleaning
t1=t.copy()
a=t.drop(columns =['Name','Number'])
a

,Team,Position,Age,Height,Weight,College,Salary
0,Boston Celtics,PG,25.0,6-2,180.0,Texas,7730337.0
1,Boston Celtics,SF,25.0,6-6,235.0,Marquette,6796117.0
2,Boston Celtics,SG,27.0,6-5,205.0,Boston University,NaN
3,Boston Celtics,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Boston Celtics,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...
452,Utah Jazz,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Utah Jazz,PG,26.0,6-3,203.0,Butler,2433333.0
454,Utah Jazz,PG,24.0,6-1,179.0,NaN,900000.0
455,Utah Jazz,C,26.0,7-3,256.0,NaN,2900000.0
456,Utah Jazz,C,26.0,7-0,231.0,Kansas,947276.0

In [13]:
t.sample()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,6-8,225.0,North Carolina,3873398.0

In [14]:
t.sample(14)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
192,Stanley Johnson,Detroit Pistons,3.0,SF,20.0,6-7,245.0,Arizona,2841960.0
308,David West,San Antonio Spurs,30.0,PF,35.0,6-9,250.0,Xavier,1499187.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,NaN,8333334.0
186,Kentavious Caldwell-Pope,Detroit Pistons,5.0,SG,23.0,6-5,205.0,Georgia,2891760.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
274,Brandan Wright,Memphis Grizzlies,34.0,PF,28.0,6-10,210.0,North Carolina,5464000.0
120,Nick Young,Los Angeles Lakers,0.0,SF,31.0,6-7,210.0,USC,5219169.0
260,Matt Barnes,Memphis Grizzlies,22.0,SF,36.0,6-7,226.0,UCLA,3542500.0
194,Marcus Morris,Detroit Pistons,13.0,PF,26.0,6-9,235.0,Kansas,5000000.0
88,Marreese Speights,Golden State Warriors,5.0,C,28.0,6-10,255.0,Florida,3815000.0

In [15]:
t.index

RangeIndex(start=0, stop=457, step=1)

In [16]:
#t.Salary.fillna(method='bfill',inplace=True)
#t

In [17]:
#var=pd.read_csv(r'https://raw.githubusercontent.com/arangodb/example-datasets/refs/heads/master/Airports/airports.csv')
#var

In [18]:
t.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [19]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [20]:
t.count()

Name        457
Team        457
Number      457
Position    457
Age         457
Height      457
Weight      457
College     373
Salary      446
dtype: int64

In [21]:
#handling of missing dat

In [22]:
t.isnull().sum()

Name         0
Team         0
Number       0
Position     0
Age          0
Height       0
Weight       0
College     84
Salary      11
dtype: int64

In [23]:
round (t.isnull().sum()/len(t)*100,2)

Name         0.00
Team         0.00
Number       0.00
Position     0.00
Age          0.00
Height       0.00
Weight       0.00
College     18.38
Salary       2.41
dtype: float64

In [24]:
t[t.Salary . isnull()]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN

observation :all the player which taller or equal to 6.2Salary data missing .

In [25]:
def heighttoCenti(data):

  v = data.split('-')

  footcm = int(v[0])*30.48

  inchcm = int(v[1])*2.54

  return footcm + inchcm

t ['Height_cm'] = t .Height.apply(heighttoCenti)
t

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Height_cm
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,187.96
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,198.12
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,195.58
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,195.58
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,208.28
...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,208.28
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,190.50
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,185.42
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,220.98
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,213.36

In [26]:
  t .drop('Height', axis=1)

,Name,Team,Number,Position,Age,Weight,College,Salary,Height_cm
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,180.0,Texas,7730337.0,187.96
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,235.0,Marquette,6796117.0,198.12
2,John Holland,Boston Celtics,30.0,SG,27.0,205.0,Boston University,NaN,195.58
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,185.0,Georgia State,1148640.0,195.58
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,231.0,NaN,5000000.0,208.28
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,234.0,Kentucky,2239800.0,208.28
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,203.0,Butler,2433333.0,190.50
454,Raul Neto,Utah Jazz,25.0,PG,24.0,179.0,NaN,900000.0,185.42
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,256.0,NaN,2900000.0,220.98
456,Jeff Withey,Utah Jazz,24.0,C,26.0,231.0,Kansas,947276.0,213.36

In [27]:
t [t .Height_cm >= 188.976]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Height_cm
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,198.12
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,195.58
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,195.58
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,208.28
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,205.74
...,...,...,...,...,...,...,...,...,...,...
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,198.12
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,208.28
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,190.50
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,220.98
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,213.36

In [28]:
def lbstoKG(data):

  v = data*0.453592

  return v

t['Weight_kg'] = t.Weight.apply(lbstoKG)

In [29]:
   t.drop('Weight', axis=1)

,Name,Team,Number,Position,Age,Height,College,Salary,Height_cm,Weight_kg
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,Texas,7730337.0,187.96,81.646560
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,Marquette,6796117.0,198.12,106.594120
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,Boston University,NaN,195.58,92.986360
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,Georgia State,1148640.0,195.58,83.914520
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,NaN,5000000.0,208.28,104.779752
...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,Kentucky,2239800.0,208.28,106.140528
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,Butler,2433333.0,190.50,92.079176
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,NaN,900000.0,185.42,81.192968
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,NaN,2900000.0,220.98,116.119552
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,Kansas,947276.0,213.36,104.779752

In [30]:
def lbstoKG(data):
  v = data * 0.453592
  return v

t['Weight_kg'] = t.Weight.apply(lbstoKG)
t = t.drop('Weight', axis=1)
t

,Name,Team,Number,Position,Age,Height,College,Salary,Height_cm,Weight_kg
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,Texas,7730337.0,187.96,81.646560
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,Marquette,6796117.0,198.12,106.594120
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,Boston University,NaN,195.58,92.986360
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,Georgia State,1148640.0,195.58,83.914520
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,NaN,5000000.0,208.28,104.779752
...,...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,Kentucky,2239800.0,208.28,106.140528
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,Butler,2433333.0,190.50,92.079176
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,NaN,900000.0,185.42,81.192968
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,NaN,2900000.0,220.98,116.119552
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,Kansas,947276.0,213.36,104.779752

In [31]:
t.Height_cm.unique()

array([187.96, 198.12, 195.58, 208.28, 205.74, 203.2 , 213.36, 193.04,
       175.26, 200.66, 190.5 , 180.34, 210.82, 220.98, 182.88, 218.44,
       185.42, 215.9 ])